[package]
name = "simple-md"
version = "0.1.0"
edition = "2021"

[dependencies]
comrak = "0.23.0"
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.202"
serde_json = "1.0.117"


[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]
